Fix conflicts with other plugins
This plugin causes a conflict with other plugins that use the gform_merge_tag_filter and require all 6 variables, including `$format`.

    add_filter( 'gform_merge_tag_filter', 'my_gform_merge_tag_filter', 10, 6 ); // PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function my_gform_merge_tag_filter

This should be a relatively simple change, by supplying that the format is "html".